version: "3"
services:
      
  lancache:
    restart: unless-stopped
    image: pegasy/lancachenet_monolithic:latest 
    environment:
      - CACHE_DISK_SIZE=1750g # Max. speicher (varriert je nach model (mögliche vars = m, ,g t ))

      - NGINX_WORKER_PROCESSES=8 
      - CACHE_SLICE_SIZE=4m 

    volumes:
      - /media/oxData:/data/cache # docker volumes für cache daten
      - /media/oxLogs:/data/logs  # /meida/ox* ist mit ssd/hdd gemounted
    ports:
      - "80:80"

  sniproxy:
    restart: unless-stopped
    image: pegasy/lancachenet_sniproxy:latest 
    environment:
      - UPSTREAM_DNS=1.1.1.1 
    ports:
      - "443:443"